services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    App\Tests\Behat\FixturesContext:
        arguments:
            $aliceFixturesLoader: '@hautelook_alice.loader'
